### PR TITLE
Added a Wrapper component

### PR DESCRIPTION
**Pull request by alexlouden**
Just playing around with this a bit, saw on twitter you're probably doing the same but thought it couldn't hurt!

### CODE REVIEW

**Comment by alexlouden** [comment]
I think the difference is that I added `wrapPageElement` to `gatsby-ssr.js` too - so it should render styles server-side (which might be what's causing your `FOUC`)

**Comment by kyleshevlin** [comment]
There's an interesting problem that SSR doesn't run in `gatsby develop` so I'm struggling wanting to implement styling solutions that depend on it.

**Comment by kyleshevlin** [comment]
Yes, unless something's wrong in my environment, anything I do in SSR doesn't do anything when working in development. I have no way to test this but to deploy it, and a solution that leaves me developing a styleless dev environment is not acceptable. 😦

**Comment by alexlouden** [comment]
Ah I didn't get that!

screen shot 2019-01-10 at 3 31 49 pm

**Comment by alexlouden** [comment]
I think the difference might be that in my fork the <Wrapper> component just has the styles - I left the Layout as is. That way all the pages are wrapped with the styles with wrapPageElement - in gatsby-browser and -ssr:

screen shot 2019-01-10 at 2 56 01 pm

**Comment by kyleshevlin** [comment]
Well that does leave me frustrated, because this is what happens in my environment. Trying to log out during hooks in `gatsby-ssr.js` does nothing, which made me conclude that they do not run in dev.
screen shot 2019-01-09 at 11 36 08 pm

**Comment by alexlouden** [comment]
How odd! Could you try cloning my fork to see if it behaves any differently locally?

**Comment by kyleshevlin** [comment]
The difference was that I was only injecting the wrapper in one or the other, and you did it in both. That teaches me a valuable lesson. I don't know why but I assumed given that it wouldn't mount/remount that SSR should cover the problem.

**Comment by alexlouden** [comment]
Ah right - good find! So it's working for you now? Yeah, I had a read of the [gatsby-plugin-layout](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-layout/src) and that's what they did so I did the same!

**Comment by kyleshevlin** [comment]
Makes sense to me. Thanks for your work. I think I done messed up the history way too much to merge this, but your work helped me come up with a solution. Thanks for all your help Alex, you ever make it to Portland, drinks are on me 👍

**Comment by alexlouden** [comment]
No worries, glad I could help!

**Pull request closed without merging**
